import React from 'react';
import { View, Text, ScrollView, StyleSheet, TouchableOpacity } from 'react-native';
import { useTheme } from '@/hooks/use-theme';
import { Card } from '@/components/ui/Card';
import { ChevronDown, Mail, Phone, BookOpen, MessageCircle } from 'lucide-react-native';

const FAQS = [
  {
    q: "How do I apply for leave?",
    a: "Navigate to the Leave tab on your dashboard, click '+ Apply Leave', select your dates and leave type, and submit. Your manager will review it."
  },
  {
    q: "When is payroll processed?",
    a: "Payroll is generated by HR on the 25th of every month. Payslips will appear in your Salary tab automatically once distributed."
  },
  {
    q: "How do I correct a missed clock-in?",
    a: "Go to the Attendance tab and click 'New Request' to submit an attendance regularization request for your manager's approval."
  },
  {
    q: "How do I update my bank details?",
    a: "Go to Settings > Profile (or your Onboarding Wizard) to securely update your direct deposit information."
  }
];

export function HelpCenter() {
  const colors = useTheme();

  return (
    <ScrollView contentContainerStyle={styles.container}>
      {/* Header */}
      <View style={styles.header}>
        <Text style={[styles.title, { color: colors.text }]}>Help Center</Text>
        <Text style={[styles.subtitle, { color: colors.textSecondary }]}>
          Find answers to common questions or reach out to support.
        </Text>
      </View>

      {/* Quick Actions */}
      <View style={styles.grid}>
        <Card style={styles.quickCard}>
          <View style={[styles.iconCircle, { backgroundColor: colors.primary + '1A' }]}>
            <BookOpen color={colors.primary} size={24} />
          </View>
          <Text style={[styles.quickCardTitle, { color: colors.text }]}>Employee Guide</Text>
          <Text style={{ color: colors.textSecondary, fontSize: 13, textAlign: 'center', marginTop: 4 }}>
            Read the full company policy manual.
          </Text>
        </Card>

        <Card style={styles.quickCard}>
          <View style={[styles.iconCircle, { backgroundColor: colors.success + '1A' }]}>
            <MessageCircle color={colors.success} size={24} />
          </View>
          <Text style={[styles.quickCardTitle, { color: colors.text }]}>IT Support</Text>
          <Text style={{ color: colors.textSecondary, fontSize: 13, textAlign: 'center', marginTop: 4 }}>
            Submit a ticket for hardware/software issues.
          </Text>
        </Card>
      </View>

      {/* FAQs */}
      <Text style={[styles.sectionTitle, { color: colors.text }]}>Frequently Asked Questions</Text>
      <Card style={styles.faqCard}>
        {FAQS.map((faq, index) => (
          <View key={index} style={[styles.faqItem, index !== FAQS.length - 1 && { borderBottomWidth: 1, borderBottomColor: colors.border }]}>
            <View style={styles.faqHeader}>
              <Text style={[styles.faqQ, { color: colors.text }]}>{faq.q}</Text>
            </View>
            <Text style={[styles.faqA, { color: colors.textSecondary }]}>{faq.a}</Text>
          </View>
        ))}
      </Card>

      {/* Contact Support */}
      <Text style={[styles.sectionTitle, { color: colors.text, marginTop: 24 }]}>Still need help?</Text>
      <Card style={styles.contactCard}>
        <View style={styles.contactRow}>
          <Mail color={colors.textSecondary} size={20} />
          <Text style={[styles.contactText, { color: colors.text }]}>support@subedge.com</Text>
        </View>
        <View style={styles.contactRow}>
          <Phone color={colors.textSecondary} size={20} />
          <Text style={[styles.contactText, { color: colors.text }]}>Subedge Technology Pvt Ltd · Bengaluru & Bhubaneswar</Text>
        </View>
      </Card>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    padding: 24,
    maxWidth: 900,
    width: '100%',
    alignSelf: 'center',
  },
  header: { marginBottom: 32 },
  title: { fontSize: 28, fontWeight: '800', marginBottom: 8 },
  subtitle: { fontSize: 16 },
  
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    marginBottom: 32,
  },
  quickCard: {
    flex: 1,
    minWidth: 250,
    alignItems: 'center',
    padding: 24,
  },
  iconCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  quickCardTitle: {
    fontSize: 16,
    fontWeight: '700',
  },

  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 16,
  },
  faqCard: {
    padding: 0,
    overflow: 'hidden',
  },
  faqItem: {
    padding: 20,
  },
  faqHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  faqQ: {
    fontSize: 16,
    fontWeight: '600',
    flex: 1,
  },
  faqA: {
    fontSize: 15,
    lineHeight: 22,
  },

  contactCard: {
    padding: 20,
    gap: 16,
  },
  contactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  contactText: {
    fontSize: 16,
    fontWeight: '500',
  }
});
